name: Module CI/CD

on: 
  push:
    tags:
      - '\d+\.\d+\.\d+' # If we tag a push with 0.0.0, create a release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: write
  attestations: write

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    
    - uses: actions/setup-node@v4

    # Update the version in module.json
    - name: Update version in module.json
      uses: restackio/update-json-file-action@2.1
      with: 
        file: ./module.json
        fields: >
          {
            "version": "${{ github.ref_name }}", 
            "manifest": "https://github.com/${{github.repository}}/releases/latest/download/module.json", 
            "download": "https://github.com/${{github.repository}}/releases/download/${{ github.ref_name}}/module.zip"
          }

    # Run the build
    - name: Build
      run: npm install && npm run build

    # create a zip file with all files required by the module to add to the release
    - name: Zip Files
      working-directory: ./dist 
      run: zip -r module .

    # attest the build
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: './dist/module.zip'
    
    # attest the module definition
    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-path: './dist/module.json'
    
    # Create a release for this specific version
    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        artifacts: './dist/module.json,./dist/module.zip'
        makeLatest: true
        tag: ${{ github.ref_name }}

    - name: Publish Module to FoundryVTT Website
      id: publish-to-foundry-website
      uses: cs96and/FoundryVTT-release-package@v1
      with:
        package-token: ${{ secrets.PACKAGE_TOKEN }}
        manifest-url: https://github.com/${{github.repository}}/releases/download/${{github.ref_name}}/module.json
