name: Module CI/CD

on: 
  push:
    tags:
      - '\d+\.\d+\.\d+' # If we tag a release with v0.0.whatever, create a release

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    
    - uses: actions/setup-node@v4

    # Update the version in module.json
    - name: Update version in module.json
      uses: restackio/update-json-file-action@2.1
      with: 
        file: ./module.json
        fields: "{\"version\": \"${{ github.ref_name }}\"}"

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: './module.json'
      env:
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{ github.ref_name}}/module.zip
    
    # Run the build
    - name: Build
      run: npm install && npm run build

    # create a zip file with all files required by the module to add to the release
    - name: Zip Files
      working-directory: ./dist 
      run: zip -r module .

    - name: view all files
      shell: bash
      run: ls -lahR

    # Update the 'latest' release
    - name: Update Latest Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false
        makeLatest: true
        draft: false
        prerelease: false
        artifacts: './dist/module.json, ./dist/module.zip'
        tag: latest

    # Create a release for this specific version
    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: false # set this to false if you want to prevent updating existing releases
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './dist/module.json,./module.zip'
        tag: ${{ github.ref_name }}
